// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserPlatformTokensColumns holds the columns for the "user_platform_tokens" table.
	UserPlatformTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeUint8},
		{Name: "user_id", Type: field.TypeString},
		{Name: "device_id", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
		{Name: "app_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserPlatformTokensTable holds the schema information for the "user_platform_tokens" table.
	UserPlatformTokensTable = &schema.Table{
		Name:        "user_platform_tokens",
		Columns:     UserPlatformTokensColumns,
		PrimaryKey:  []*schema.Column{UserPlatformTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UserPushTokensColumns holds the columns for the "user_push_tokens" table.
	UserPushTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "token", Type: field.TypeString},
		{Name: "app_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserPushTokensTable holds the schema information for the "user_push_tokens" table.
	UserPushTokensTable = &schema.Table{
		Name:        "user_push_tokens",
		Columns:     UserPushTokensColumns,
		PrimaryKey:  []*schema.Column{UserPushTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserPlatformTokensTable,
		UserPushTokensTable,
	}
)

func init() {
}
