// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/shitamachi/push-service/ent/migrate"

	"github.com/shitamachi/push-service/ent/userplatformtokens"
	"github.com/shitamachi/push-service/ent/userpushtoken"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// UserPlatformTokens is the client for interacting with the UserPlatformTokens builders.
	UserPlatformTokens *UserPlatformTokensClient
	// UserPushToken is the client for interacting with the UserPushToken builders.
	UserPushToken *UserPushTokenClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.UserPlatformTokens = NewUserPlatformTokensClient(c.config)
	c.UserPushToken = NewUserPushTokenClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		UserPlatformTokens: NewUserPlatformTokensClient(cfg),
		UserPushToken:      NewUserPushTokenClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:             cfg,
		UserPlatformTokens: NewUserPlatformTokensClient(cfg),
		UserPushToken:      NewUserPushTokenClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		UserPlatformTokens.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.UserPlatformTokens.Use(hooks...)
	c.UserPushToken.Use(hooks...)
}

// UserPlatformTokensClient is a client for the UserPlatformTokens schema.
type UserPlatformTokensClient struct {
	config
}

// NewUserPlatformTokensClient returns a client for the UserPlatformTokens from the given config.
func NewUserPlatformTokensClient(c config) *UserPlatformTokensClient {
	return &UserPlatformTokensClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userplatformtokens.Hooks(f(g(h())))`.
func (c *UserPlatformTokensClient) Use(hooks ...Hook) {
	c.hooks.UserPlatformTokens = append(c.hooks.UserPlatformTokens, hooks...)
}

// Create returns a create builder for UserPlatformTokens.
func (c *UserPlatformTokensClient) Create() *UserPlatformTokensCreate {
	mutation := newUserPlatformTokensMutation(c.config, OpCreate)
	return &UserPlatformTokensCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserPlatformTokens entities.
func (c *UserPlatformTokensClient) CreateBulk(builders ...*UserPlatformTokensCreate) *UserPlatformTokensCreateBulk {
	return &UserPlatformTokensCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserPlatformTokens.
func (c *UserPlatformTokensClient) Update() *UserPlatformTokensUpdate {
	mutation := newUserPlatformTokensMutation(c.config, OpUpdate)
	return &UserPlatformTokensUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserPlatformTokensClient) UpdateOne(upt *UserPlatformTokens) *UserPlatformTokensUpdateOne {
	mutation := newUserPlatformTokensMutation(c.config, OpUpdateOne, withUserPlatformTokens(upt))
	return &UserPlatformTokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserPlatformTokensClient) UpdateOneID(id int) *UserPlatformTokensUpdateOne {
	mutation := newUserPlatformTokensMutation(c.config, OpUpdateOne, withUserPlatformTokensID(id))
	return &UserPlatformTokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserPlatformTokens.
func (c *UserPlatformTokensClient) Delete() *UserPlatformTokensDelete {
	mutation := newUserPlatformTokensMutation(c.config, OpDelete)
	return &UserPlatformTokensDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserPlatformTokensClient) DeleteOne(upt *UserPlatformTokens) *UserPlatformTokensDeleteOne {
	return c.DeleteOneID(upt.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserPlatformTokensClient) DeleteOneID(id int) *UserPlatformTokensDeleteOne {
	builder := c.Delete().Where(userplatformtokens.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserPlatformTokensDeleteOne{builder}
}

// Query returns a query builder for UserPlatformTokens.
func (c *UserPlatformTokensClient) Query() *UserPlatformTokensQuery {
	return &UserPlatformTokensQuery{
		config: c.config,
	}
}

// Get returns a UserPlatformTokens entity by its id.
func (c *UserPlatformTokensClient) Get(ctx context.Context, id int) (*UserPlatformTokens, error) {
	return c.Query().Where(userplatformtokens.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserPlatformTokensClient) GetX(ctx context.Context, id int) *UserPlatformTokens {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserPlatformTokensClient) Hooks() []Hook {
	return c.hooks.UserPlatformTokens
}

// UserPushTokenClient is a client for the UserPushToken schema.
type UserPushTokenClient struct {
	config
}

// NewUserPushTokenClient returns a client for the UserPushToken from the given config.
func NewUserPushTokenClient(c config) *UserPushTokenClient {
	return &UserPushTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userpushtoken.Hooks(f(g(h())))`.
func (c *UserPushTokenClient) Use(hooks ...Hook) {
	c.hooks.UserPushToken = append(c.hooks.UserPushToken, hooks...)
}

// Create returns a create builder for UserPushToken.
func (c *UserPushTokenClient) Create() *UserPushTokenCreate {
	mutation := newUserPushTokenMutation(c.config, OpCreate)
	return &UserPushTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserPushToken entities.
func (c *UserPushTokenClient) CreateBulk(builders ...*UserPushTokenCreate) *UserPushTokenCreateBulk {
	return &UserPushTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserPushToken.
func (c *UserPushTokenClient) Update() *UserPushTokenUpdate {
	mutation := newUserPushTokenMutation(c.config, OpUpdate)
	return &UserPushTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserPushTokenClient) UpdateOne(upt *UserPushToken) *UserPushTokenUpdateOne {
	mutation := newUserPushTokenMutation(c.config, OpUpdateOne, withUserPushToken(upt))
	return &UserPushTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserPushTokenClient) UpdateOneID(id int) *UserPushTokenUpdateOne {
	mutation := newUserPushTokenMutation(c.config, OpUpdateOne, withUserPushTokenID(id))
	return &UserPushTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserPushToken.
func (c *UserPushTokenClient) Delete() *UserPushTokenDelete {
	mutation := newUserPushTokenMutation(c.config, OpDelete)
	return &UserPushTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserPushTokenClient) DeleteOne(upt *UserPushToken) *UserPushTokenDeleteOne {
	return c.DeleteOneID(upt.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserPushTokenClient) DeleteOneID(id int) *UserPushTokenDeleteOne {
	builder := c.Delete().Where(userpushtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserPushTokenDeleteOne{builder}
}

// Query returns a query builder for UserPushToken.
func (c *UserPushTokenClient) Query() *UserPushTokenQuery {
	return &UserPushTokenQuery{
		config: c.config,
	}
}

// Get returns a UserPushToken entity by its id.
func (c *UserPushTokenClient) Get(ctx context.Context, id int) (*UserPushToken, error) {
	return c.Query().Where(userpushtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserPushTokenClient) GetX(ctx context.Context, id int) *UserPushToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserPushTokenClient) Hooks() []Hook {
	return c.hooks.UserPushToken
}
