// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/shitamachi/push-service/ent/schema"
	"github.com/shitamachi/push-service/ent/userpushtoken"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userpushtokenFields := schema.UserPushToken{}.Fields()
	_ = userpushtokenFields
	// userpushtokenDescCreatedAt is the schema descriptor for created_at field.
	userpushtokenDescCreatedAt := userpushtokenFields[3].Descriptor()
	// userpushtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	userpushtoken.DefaultCreatedAt = userpushtokenDescCreatedAt.Default.(func() time.Time)
	// userpushtokenDescUpdatedAt is the schema descriptor for updated_at field.
	userpushtokenDescUpdatedAt := userpushtokenFields[4].Descriptor()
	// userpushtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userpushtoken.DefaultUpdatedAt = userpushtokenDescUpdatedAt.Default.(func() time.Time)
	// userpushtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userpushtoken.UpdateDefaultUpdatedAt = userpushtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
}
