// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shitamachi/push-service/ent/predicate"
	"github.com/shitamachi/push-service/ent/userplatformtokens"
)

// UserPlatformTokensQuery is the builder for querying UserPlatformTokens entities.
type UserPlatformTokensQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserPlatformTokens
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserPlatformTokensQuery builder.
func (uptq *UserPlatformTokensQuery) Where(ps ...predicate.UserPlatformTokens) *UserPlatformTokensQuery {
	uptq.predicates = append(uptq.predicates, ps...)
	return uptq
}

// Limit adds a limit step to the query.
func (uptq *UserPlatformTokensQuery) Limit(limit int) *UserPlatformTokensQuery {
	uptq.limit = &limit
	return uptq
}

// Offset adds an offset step to the query.
func (uptq *UserPlatformTokensQuery) Offset(offset int) *UserPlatformTokensQuery {
	uptq.offset = &offset
	return uptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uptq *UserPlatformTokensQuery) Unique(unique bool) *UserPlatformTokensQuery {
	uptq.unique = &unique
	return uptq
}

// Order adds an order step to the query.
func (uptq *UserPlatformTokensQuery) Order(o ...OrderFunc) *UserPlatformTokensQuery {
	uptq.order = append(uptq.order, o...)
	return uptq
}

// First returns the first UserPlatformTokens entity from the query.
// Returns a *NotFoundError when no UserPlatformTokens was found.
func (uptq *UserPlatformTokensQuery) First(ctx context.Context) (*UserPlatformTokens, error) {
	nodes, err := uptq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userplatformtokens.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) FirstX(ctx context.Context) *UserPlatformTokens {
	node, err := uptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserPlatformTokens ID from the query.
// Returns a *NotFoundError when no UserPlatformTokens ID was found.
func (uptq *UserPlatformTokensQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uptq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userplatformtokens.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) FirstIDX(ctx context.Context) int {
	id, err := uptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserPlatformTokens entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserPlatformTokens entity is not found.
// Returns a *NotFoundError when no UserPlatformTokens entities are found.
func (uptq *UserPlatformTokensQuery) Only(ctx context.Context) (*UserPlatformTokens, error) {
	nodes, err := uptq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userplatformtokens.Label}
	default:
		return nil, &NotSingularError{userplatformtokens.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) OnlyX(ctx context.Context) *UserPlatformTokens {
	node, err := uptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserPlatformTokens ID in the query.
// Returns a *NotSingularError when exactly one UserPlatformTokens ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uptq *UserPlatformTokensQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uptq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = &NotSingularError{userplatformtokens.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) OnlyIDX(ctx context.Context) int {
	id, err := uptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserPlatformTokensSlice.
func (uptq *UserPlatformTokensQuery) All(ctx context.Context) ([]*UserPlatformTokens, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uptq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) AllX(ctx context.Context) []*UserPlatformTokens {
	nodes, err := uptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserPlatformTokens IDs.
func (uptq *UserPlatformTokensQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uptq.Select(userplatformtokens.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) IDsX(ctx context.Context) []int {
	ids, err := uptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uptq *UserPlatformTokensQuery) Count(ctx context.Context) (int, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uptq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) CountX(ctx context.Context) int {
	count, err := uptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uptq *UserPlatformTokensQuery) Exist(ctx context.Context) (bool, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uptq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uptq *UserPlatformTokensQuery) ExistX(ctx context.Context) bool {
	exist, err := uptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserPlatformTokensQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uptq *UserPlatformTokensQuery) Clone() *UserPlatformTokensQuery {
	if uptq == nil {
		return nil
	}
	return &UserPlatformTokensQuery{
		config:     uptq.config,
		limit:      uptq.limit,
		offset:     uptq.offset,
		order:      append([]OrderFunc{}, uptq.order...),
		predicates: append([]predicate.UserPlatformTokens{}, uptq.predicates...),
		// clone intermediate query.
		sql:  uptq.sql.Clone(),
		path: uptq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type uint8 `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserPlatformTokens.Query().
//		GroupBy(userplatformtokens.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uptq *UserPlatformTokensQuery) GroupBy(field string, fields ...string) *UserPlatformTokensGroupBy {
	group := &UserPlatformTokensGroupBy{config: uptq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uptq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type uint8 `json:"type,omitempty"`
//	}
//
//	client.UserPlatformTokens.Query().
//		Select(userplatformtokens.FieldType).
//		Scan(ctx, &v)
//
func (uptq *UserPlatformTokensQuery) Select(field string, fields ...string) *UserPlatformTokensSelect {
	uptq.fields = append([]string{field}, fields...)
	return &UserPlatformTokensSelect{UserPlatformTokensQuery: uptq}
}

func (uptq *UserPlatformTokensQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uptq.fields {
		if !userplatformtokens.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uptq.path != nil {
		prev, err := uptq.path(ctx)
		if err != nil {
			return err
		}
		uptq.sql = prev
	}
	return nil
}

func (uptq *UserPlatformTokensQuery) sqlAll(ctx context.Context) ([]*UserPlatformTokens, error) {
	var (
		nodes = []*UserPlatformTokens{}
		_spec = uptq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserPlatformTokens{config: uptq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uptq *UserPlatformTokensQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uptq.querySpec()
	return sqlgraph.CountNodes(ctx, uptq.driver, _spec)
}

func (uptq *UserPlatformTokensQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uptq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uptq *UserPlatformTokensQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userplatformtokens.Table,
			Columns: userplatformtokens.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userplatformtokens.FieldID,
			},
		},
		From:   uptq.sql,
		Unique: true,
	}
	if unique := uptq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uptq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userplatformtokens.FieldID)
		for i := range fields {
			if fields[i] != userplatformtokens.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uptq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uptq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uptq *UserPlatformTokensQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uptq.driver.Dialect())
	t1 := builder.Table(userplatformtokens.Table)
	selector := builder.Select(t1.Columns(userplatformtokens.Columns...)...).From(t1)
	if uptq.sql != nil {
		selector = uptq.sql
		selector.Select(selector.Columns(userplatformtokens.Columns...)...)
	}
	for _, p := range uptq.predicates {
		p(selector)
	}
	for _, p := range uptq.order {
		p(selector)
	}
	if offset := uptq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uptq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserPlatformTokensGroupBy is the group-by builder for UserPlatformTokens entities.
type UserPlatformTokensGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uptgb *UserPlatformTokensGroupBy) Aggregate(fns ...AggregateFunc) *UserPlatformTokensGroupBy {
	uptgb.fns = append(uptgb.fns, fns...)
	return uptgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uptgb *UserPlatformTokensGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uptgb.path(ctx)
	if err != nil {
		return err
	}
	uptgb.sql = query
	return uptgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uptgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) StringsX(ctx context.Context) []string {
	v, err := uptgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uptgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) StringX(ctx context.Context) string {
	v, err := uptgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) IntsX(ctx context.Context) []int {
	v, err := uptgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uptgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) IntX(ctx context.Context) int {
	v, err := uptgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uptgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uptgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uptgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uptgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UserPlatformTokensGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uptgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uptgb *UserPlatformTokensGroupBy) BoolX(ctx context.Context) bool {
	v, err := uptgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uptgb *UserPlatformTokensGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uptgb.fields {
		if !userplatformtokens.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uptgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uptgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uptgb *UserPlatformTokensGroupBy) sqlQuery() *sql.Selector {
	selector := uptgb.sql
	columns := make([]string, 0, len(uptgb.fields)+len(uptgb.fns))
	columns = append(columns, uptgb.fields...)
	for _, fn := range uptgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(uptgb.fields...)
}

// UserPlatformTokensSelect is the builder for selecting fields of UserPlatformTokens entities.
type UserPlatformTokensSelect struct {
	*UserPlatformTokensQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (upts *UserPlatformTokensSelect) Scan(ctx context.Context, v interface{}) error {
	if err := upts.prepareQuery(ctx); err != nil {
		return err
	}
	upts.sql = upts.UserPlatformTokensQuery.sqlQuery(ctx)
	return upts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) ScanX(ctx context.Context, v interface{}) {
	if err := upts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Strings(ctx context.Context) ([]string, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) StringsX(ctx context.Context) []string {
	v, err := upts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) StringX(ctx context.Context) string {
	v, err := upts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Ints(ctx context.Context) ([]int, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) IntsX(ctx context.Context) []int {
	v, err := upts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) IntX(ctx context.Context) int {
	v, err := upts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) Float64sX(ctx context.Context) []float64 {
	v, err := upts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) Float64X(ctx context.Context) float64 {
	v, err := upts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UserPlatformTokensSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) BoolsX(ctx context.Context) []bool {
	v, err := upts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (upts *UserPlatformTokensSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userplatformtokens.Label}
	default:
		err = fmt.Errorf("ent: UserPlatformTokensSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upts *UserPlatformTokensSelect) BoolX(ctx context.Context) bool {
	v, err := upts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upts *UserPlatformTokensSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := upts.sqlQuery().Query()
	if err := upts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upts *UserPlatformTokensSelect) sqlQuery() sql.Querier {
	selector := upts.sql
	selector.Select(selector.Columns(upts.fields...)...)
	return selector
}
