// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shitamachi/push-service/ent/userplatformtokens"
)

// UserPlatformTokensCreate is the builder for creating a UserPlatformTokens entity.
type UserPlatformTokensCreate struct {
	config
	mutation *UserPlatformTokensMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (uptc *UserPlatformTokensCreate) SetType(u uint8) *UserPlatformTokensCreate {
	uptc.mutation.SetType(u)
	return uptc
}

// SetUserID sets the "user_id" field.
func (uptc *UserPlatformTokensCreate) SetUserID(s string) *UserPlatformTokensCreate {
	uptc.mutation.SetUserID(s)
	return uptc
}

// SetDeviceID sets the "device_id" field.
func (uptc *UserPlatformTokensCreate) SetDeviceID(s string) *UserPlatformTokensCreate {
	uptc.mutation.SetDeviceID(s)
	return uptc
}

// SetToken sets the "token" field.
func (uptc *UserPlatformTokensCreate) SetToken(s string) *UserPlatformTokensCreate {
	uptc.mutation.SetToken(s)
	return uptc
}

// SetAppID sets the "app_id" field.
func (uptc *UserPlatformTokensCreate) SetAppID(s string) *UserPlatformTokensCreate {
	uptc.mutation.SetAppID(s)
	return uptc
}

// SetCreatedAt sets the "created_at" field.
func (uptc *UserPlatformTokensCreate) SetCreatedAt(t time.Time) *UserPlatformTokensCreate {
	uptc.mutation.SetCreatedAt(t)
	return uptc
}

// SetUpdatedAt sets the "updated_at" field.
func (uptc *UserPlatformTokensCreate) SetUpdatedAt(t time.Time) *UserPlatformTokensCreate {
	uptc.mutation.SetUpdatedAt(t)
	return uptc
}

// Mutation returns the UserPlatformTokensMutation object of the builder.
func (uptc *UserPlatformTokensCreate) Mutation() *UserPlatformTokensMutation {
	return uptc.mutation
}

// Save creates the UserPlatformTokens in the database.
func (uptc *UserPlatformTokensCreate) Save(ctx context.Context) (*UserPlatformTokens, error) {
	var (
		err  error
		node *UserPlatformTokens
	)
	if len(uptc.hooks) == 0 {
		if err = uptc.check(); err != nil {
			return nil, err
		}
		node, err = uptc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserPlatformTokensMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uptc.check(); err != nil {
				return nil, err
			}
			uptc.mutation = mutation
			node, err = uptc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uptc.hooks) - 1; i >= 0; i-- {
			mut = uptc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uptc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uptc *UserPlatformTokensCreate) SaveX(ctx context.Context) *UserPlatformTokens {
	v, err := uptc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (uptc *UserPlatformTokensCreate) check() error {
	if _, ok := uptc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New("ent: missing required field \"type\"")}
	}
	if _, ok := uptc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New("ent: missing required field \"user_id\"")}
	}
	if _, ok := uptc.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New("ent: missing required field \"device_id\"")}
	}
	if _, ok := uptc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New("ent: missing required field \"token\"")}
	}
	if _, ok := uptc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New("ent: missing required field \"app_id\"")}
	}
	if _, ok := uptc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := uptc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	return nil
}

func (uptc *UserPlatformTokensCreate) sqlSave(ctx context.Context) (*UserPlatformTokens, error) {
	_node, _spec := uptc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uptc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uptc *UserPlatformTokensCreate) createSpec() (*UserPlatformTokens, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPlatformTokens{config: uptc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userplatformtokens.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userplatformtokens.FieldID,
			},
		}
	)
	if value, ok := uptc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: userplatformtokens.FieldType,
		})
		_node.Type = value
	}
	if value, ok := uptc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userplatformtokens.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := uptc.mutation.DeviceID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userplatformtokens.FieldDeviceID,
		})
		_node.DeviceID = value
	}
	if value, ok := uptc.mutation.Token(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userplatformtokens.FieldToken,
		})
		_node.Token = value
	}
	if value, ok := uptc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userplatformtokens.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := uptc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userplatformtokens.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := uptc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userplatformtokens.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserPlatformTokensCreateBulk is the builder for creating many UserPlatformTokens entities in bulk.
type UserPlatformTokensCreateBulk struct {
	config
	builders []*UserPlatformTokensCreate
}

// Save creates the UserPlatformTokens entities in the database.
func (uptcb *UserPlatformTokensCreateBulk) Save(ctx context.Context) ([]*UserPlatformTokens, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uptcb.builders))
	nodes := make([]*UserPlatformTokens, len(uptcb.builders))
	mutators := make([]Mutator, len(uptcb.builders))
	for i := range uptcb.builders {
		func(i int, root context.Context) {
			builder := uptcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPlatformTokensMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uptcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uptcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uptcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uptcb *UserPlatformTokensCreateBulk) SaveX(ctx context.Context) []*UserPlatformTokens {
	v, err := uptcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
