basePath: /v1
definitions:
  api.ResponseEntry:
    properties:
      data:
        description: 实际的返回响应
        type: object
      message:
        description: 响应信息
        type: string
      status:
        description: 内部状态码
        type: integer
      timestamp:
        description: 响应时间戳
        type: integer
    type: object
  handler.BatchPushMessageReq:
    properties:
      global_message:
        $ref: '#/definitions/models.PushMessage'
        description: 全局的默认批量发送的消息, 如果具体的消息设置了 models.PushMessage 那么将覆盖掉此项
        type: object
      message_items:
        description: 批量发送的消息列表
        items:
          $ref: '#/definitions/handler.PushMessageReqItem'
        type: array
    type: object
  handler.BatchPushMessageRespItem:
    properties:
      app_id:
        description: app id
        type: string
      error:
        description: 错误
        type: error
      message:
        $ref: '#/definitions/models.PushMessage'
        description: 推送消息
        type: object
      platform_resp:
        description: 第三方平台的响应
        type: object
      push_status:
        description: 0 为 failed 1 为 succeed
        type: integer
      reason:
        description: 失败的原因
        type: string
      token:
        description: 设备 token
        type: string
      user_id:
        description: 用户 id
        type: string
    type: object
  handler.PushMessageForAllSpecificClientReq:
    properties:
      action_id:
        description: 本次全体推送动作的唯一 id, 用于区分每次全体推送
        type: string
      app_ids:
        description: 待发送的客户端 app id
        items:
          type: string
        type: array
      message:
        $ref: '#/definitions/models.PushMessage'
        description: 推送消息
        type: object
    type: object
  handler.PushMessageForAllSpecificClientResp:
    properties:
      action_id:
        description: 本次推送的唯一标识符
        type: string
      status:
        description: 推送状态 1为成功
        type: integer
    type: object
  handler.PushMessageReqItem:
    properties:
      app_id:
        description: app id
        type: string
      message:
        $ref: '#/definitions/models.PushMessage'
        description: 推送消息
        type: object
      token:
        description: 设备 token
        type: string
      user_id:
        description: 用户 id
        type: string
    type: object
  handler.PushMessageResp:
    properties:
      error:
        description: 假如请求失败, 返回的错误
        type: error
      platform_resp:
        description: 请求第三方平台发送推送消息,第三方平台返回的响应结果
        type: object
      push_result:
        description: 发布推送通知的响应信息
        type: string
      push_status:
        description: 0 为 failed 1 为 succeed
        type: integer
      token:
        description: 设备 token
        type: string
      user_id:
        description: 用户 id
        type: string
    type: object
  models.PushMessage:
    properties:
      body:
        description: 内容
        type: string
      data:
        additionalProperties:
          type: string
        description: |-
          客户端处理通知类型
          type: 0 无任何动作 1 打开书籍详情 2 打开一个特定的网页 3 打开新手礼包页面 4 打开奖励任务页面
          bookId: 打开书籍详情所跳转的书籍 book id
          link: 打开网页所跳转的网页URL
        type: object
      title:
        description: 标题
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: push service http server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Push Service API
  version: "1.0"
paths:
  /v1/batch_push_messages:
    post:
      consumes:
      - application/json
      description: 给客户端所有用户发送push消息; 不支持每个消息单独设置
      operationId: push-messages-for-all-users
      parameters:
      - description: 请求体
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handler.PushMessageForAllSpecificClientReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseEntry'
            - properties:
                data:
                  $ref: '#/definitions/handler.PushMessageForAllSpecificClientResp'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/api.ResponseEntry'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/api.ResponseEntry'
      summary: 给客户端所有用户发送push消息
      tags:
      - push
  /v1/push_messages:
    post:
      consumes:
      - application/json
      description: 推送单个消息
      operationId: push-messages
      parameters:
      - description: message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handler.PushMessageReqItem'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseEntry'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/handler.PushMessageResp'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/api.ResponseEntry'
        "404":
          description: 无法从请求的 user_id 或是 token 查找到对应数据
          schema:
            $ref: '#/definitions/api.ResponseEntry'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ResponseEntry'
      summary: 推送单个消息 push
      tags:
      - push
swagger: "2.0"
