// Code generated by entc, DO NOT EDIT.

package userplatformtokens

const (
	// Label holds the string label denoting the userplatformtokens type in the database.
	Label = "user_platform_tokens"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the userplatformtokens in the database.
	Table = "user_platform_tokens"
)

// Columns holds all SQL columns for userplatformtokens fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldUserID,
	FieldDeviceID,
	FieldToken,
	FieldAppID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
