// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserPlatformTokens is the predicate function for userplatformtokens builders.
type UserPlatformTokens func(*sql.Selector)

// UserPushToken is the predicate function for userpushtoken builders.
type UserPushToken func(*sql.Selector)
